import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'

export const metadata = {
  title: 'Modern React Demo',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

function TopNav() {
  return (
    <nav className="bg-gray-800 text-white border-b border-white flex w-full items-center justify-between p-4 text-xl font-semibold">
      <div>Modern React Demo</div>
      <div>Sign In</div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} flex flex-col gap-4`}>
        <TopNav />
        {children}
      </body>
    </html>
  )
}
